# Generated by Django 4.1 on 2022-10-19 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='rc_questions',
            field=models.CharField(max_length=255, null=True, verbose_name='Questões recuperadas'),
        ),
        migrations.AddField(
            model_name='team',
            name='rt_questions',
            field=models.CharField(max_length=255, null=True, verbose_name='Questões acertadas'),
        ),
        migrations.AddField(
            model_name='team',
            name='wr_questions',
            field=models.CharField(max_length=255, null=True, verbose_name='Questões erradas'),
        ),
    ]
