# Generated by Django 4.1 on 2022-10-25 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('accounts', '0002_team_rc_questions_team_rt_questions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='event',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='events.event'),
            preserve_default=False,
        ),
    ]
