# Generated by Django 4.1 on 2022-10-26 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_team_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='formated_time',
            field=models.PositiveIntegerField(null=True, verbose_name='Tempo relativo + penalidades'),
        ),
        migrations.AlterField(
            model_name='team',
            name='penalties',
            field=models.PositiveIntegerField(null=True, verbose_name='Quantidade de penalidades'),
        ),
        migrations.AlterField(
            model_name='team',
            name='relative_time',
            field=models.PositiveIntegerField(null=True, verbose_name='Tempo relativo'),
        ),
    ]
