# Generated by Django 4.1 on 2023-01-24 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_team_formated_time_alter_team_penalties_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='rc_questions',
            field=models.CharField(default='', max_length=255, verbose_name='Questões recuperadas'),
        ),
        migrations.AlterField(
            model_name='team',
            name='rt_questions',
            field=models.CharField(default='', max_length=255, verbose_name='Questões acertadas'),
        ),
        migrations.AlterField(
            model_name='team',
            name='wr_questions',
            field=models.CharField(default='', max_length=255, verbose_name='Questões erradas'),
        ),
    ]
