# Generated by Django 4.1 on 2023-01-24 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_team_rc_questions_alter_team_rt_questions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='relative_time',
            field=models.PositiveIntegerField(default=0, verbose_name='Tempo relativo'),
        ),
    ]
