# Generated by Django 4.1 on 2022-09-11 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do evento')),
                ('date', models.DateField(verbose_name='Data do evento')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Hora de início')),
                ('duration', models.PositiveIntegerField(default=1, null=True, verbose_name='Duraçao do evento em horas')),
                ('type', models.IntegerField(choices=[(0, 'Envio automático'), (1, 'Validação do juíz')], default=0, verbose_name='Tipo de submissão')),
                ('punishment_value', models.IntegerField(default=20, verbose_name='Valor em minutos de cada punição acumulada')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome da instituição')),
                ('city', models.CharField(max_length=50, verbose_name='Cidade')),
            ],
            options={
                'verbose_name': 'Instituição',
                'verbose_name_plural': 'Instituições',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qt_number', models.PositiveIntegerField(verbose_name='Número da questão')),
                ('question', models.TextField(null=True, verbose_name='Texto da questão (opcional)')),
                ('correct_ansnwer', models.CharField(max_length=1, verbose_name="Alternativa correta ('X' caso seja validação de juíz)")),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
            options={
                'verbose_name': 'Questão',
                'verbose_name_plural': 'Questões',
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=1)),
                ('time', models.TimeField(auto_now_add=True)),
                ('status', models.PositiveIntegerField(choices=[(0, 'Incorreto'), (1, 'Correto')], verbose_name='Status da subimissão')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.question')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.team')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.institution'),
        ),
        migrations.AddField(
            model_name='event',
            name='judges',
            field=models.ManyToManyField(to='accounts.judge'),
        ),
    ]
