# Generated by Django 4.1 on 2022-11-08 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('date', '-start_time'), 'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
    ]
