# Generated by Django 4.1 on 2023-04-16 18:35

import applications.events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_is_active_event_is_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='questions_pdf',
            field=models.FileField(null=True, upload_to='question_pdfs/', validators=[applications.events.models.validate_pdf]),
        ),
        migrations.AlterField(
            model_name='event',
            name='duration',
            field=models.PositiveIntegerField(default=1, null=True, verbose_name='Duraçao do evento em minutos'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(blank=True, null=True, verbose_name='Texto da questão (opcional)'),
        ),
    ]
